### ISSUE TITLE
Unify GTK2 & GTK3 bar color.

### ISSUE THREAD

**Issue by chuutatsu** [reorr/whitey#1]
In GTK2 apps it looks alright.
![1](https://user-images.githubusercontent.com/24815847/30235801-74d5db2e-9537-11e7-98e2-8230dca22ed7.png)

But in GTK3 apps it looks like this:
![2](https://user-images.githubusercontent.com/24815847/30235803-783ea886-9537-11e7-88dd-6065b14fd169.png)

Isn't Whitey supposed to be full-white? It would be nice if the black bar is also whitey. 

EDIT: The black menu bar appears in Libreoffice too. I can't give out another screenshot because my internet doesn't allow me to upload. :/

**Comment by reorr** [comment]
thank you for your comment, i've fixed it in the latest commit
![screenshot_2017-11-05_20-04-52](https://user-images.githubusercontent.com/10528000/32415095-5506e48a-c266-11e7-90d9-b25c56409113.png)
also black menu in LibreOffice has been fixed too
![screenshot_2017-11-05_20-24-53](https://user-images.githubusercontent.com/10528000/32415139-555fa25e-c267-11e7-8b31-3e1ac476f391.png)
