### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by zeroby0** [reorr/whitey#2]
Hi!

Could please also add installation instructions. I added the theme to `~/.local/share/themes` on Debian@9 but only window decorations are working. I also changed the xfce theme to Whitney, but it doesn't seem to affect anything.

Here is my screenshot.

![screenshot_2017-11-30_22-50-43](https://user-images.githubusercontent.com/16903044/33445094-0622a460-d622-11e7-8c05-ccdfbb41829a.png)

Thank you :)

**Comment by reorr** [comment]
can you tell me which version gtk2 you use?
because i'm using it by copying whitey folder to ~/.themes and work fine in my xubuntu and archlinux machine.
